font_family FiraCode Nerd Font
font_size 14.0


confirm_os_window_close 0

map ctrl+f launch --cwd=current --type=overlay sh ~/scripts/p.sh
map ctrl+s launch --cwd=current --type=overlay sh ~/scripts/test.sh



# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

enable_audio_bell no
