font_family       monospace
font_size         12.0
italic_font       auto
bold_italic_font  auto

window_padding_width 5

include themes/theme.conf
#background_opacity 0.80

confirm_os_window_close 0

map ctrl+f launch --cwd=current --type=overlay bash ~/Scripts/jumper.sh
