font_family       monospace
font_size         10.0
italic_font       auto
bold_italic_font  auto

window_padding_width 0

include themes/theme.conf

confirm_os_window_close 0
enable_audio_bell no

map ctrl+f launch --cwd=current --type=overlay bash ~/Scripts/jumper.sh
