#!/bin/bash

function capture_to_clipboard() {
    _screenshot_command_="$1"

    if [[ "$_screenshot_command_" == "full" ]]; then
        grim - | wl-copy
    elif [[ "$_screenshot_command_" == "area" ]]; then
        grim -g "$(slurp)" - | wl-copy
    else
        echo "Invalid command. Use 'full' or 'area'."
        exit 1
    fi
}

# Check the args passed
if [ -z "$1" ] || ([ "$1" != 'full' ] && [ "$1" != 'area' ]);
then
    echo "
    Requires an argument:
    area    - Area screenshot
    full    - Fullscreen screenshot
    Example:
    ./script.sh area
    ./script.sh full
    "
else
    capture_to_clipboard "$1"
fi
