1|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/evening-sky.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/sekiro.jpg
0|Decay-Green|~/.config/swww/Decay-Green/night_city.png
0|Rose-Pine|~/.config/swww/Rose-Pine/rosepine.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/tokyo_pink.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/spring_bloom.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/cyberpunk_dave.png
0|Frosted-Glass|~/.config/swww/Frosted-Glass/min_forest.jpg
