opacity-rule = [
    "90:class_g = 'kitty'",
    "90:class_g = 'discord'",
    "100:class_g = 'gromit-mpx'",
    "80:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

blur:
{
    method = "dual_kawase";
    strength = 4;
    size = 30;
}

backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'slop'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'gromit-mpx'",
    "_NET_WM_OPACITY@:c < 0x99"
];

shadow = true;
shadow-radius = 10;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = 0.1;
